### ISSUE TITLE
what is the tool which drew ZMQ figures?

### ISSUE THREAD

**Issue by QingyunLiu** [booksbyus/zguide#691]
ZMQ figures is concise and beautiful, could you tell me what's the tool which drew the figures like below:
![topo-v1](https://cloud.githubusercontent.com/assets/15082338/25428919/e29e5fe4-2aa9-11e7-8e15-4630056a04ff.png)

**Comment by sappo** [comment]
That would be asciitosvg: https://github.com/dhobsd/asciitosvg

Am 26.04.2017 11:58 schrieb "刘青云" <notifications@github.com>:

ZMQ figures is concise and beautiful, could you tell me what's the tool
which drew the figures like below:
[image: topo-v1]
<https://cloud.githubusercontent.com/assets/15082338/25428919/e29e5fe4-2aa9-11e7-8e15-4630056a04ff.png>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/booksbyus/zguide/issues/691>, or mute the thread

**Comment by QingyunLiu** [comment]
That's it! Thank you very much @sappo ! : )
