### ISSUE TITLE
Which tool/app does it use to draw diagram in The Guide of ZeroMQ

### ISSUE THREAD

**Issue by 61t** [booksbyus/zguide#717]
Which tool/app does it uses to draw diagram in The Guide of ZeroMQ?

I prefer to do prototyping the same as in The Guide, that is brilliant.

**Comment by bluca** [comment]
I haven't used it and @sappo will know better, but there's this directory in the repo: https://github.com/booksbyus/zguide/tree/master/bin/asciitosvg

**Comment by 61t** [comment]
Thanks @bluca 

ASCIIToSVG is definitely an awesome tool that help me out for inserting basic conceptual diagram/flow into markdown. 

If I cannot get any better/simple solution from @sappo , I will use web-based ascii flowchart tool referenced from external resources from link you mentioned above, then merge this cute tool ASCIIToSVG into my workflow of markdown in the near future.

**Comment by sappo** [comment]
It's asciitosvg see https://github.com/dhobsd/asciitosvg

Am 22.02.2018 6:46 nachm. schrieb "61t" <notifications@github.com>:

Thanks @bluca <https://github.com/bluca>

ASCIIToSVG is definitely an awesome tool that help me out for inserting
basic conceptual diagram/flow into markdown.

If I cannot get any better/simple solution from @sappo
<https://github.com/sappo> , I will use web-based ascii flowchart tool
referenced from external resources from link you mentioned above, then
merge this cute tool ASCIIToSVG into my workflow of markdown in the near
future.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/booksbyus/zguide/issues/717#issuecomment-367762681>,
or mute
the thread

**Comment by 61t** [comment]
@sappo Thanks, that's clear. 

Asciiflow for internal use and fast prototyping and ASCIIToSVG for blog and documents for public. Awesome 👍
