### ISSUE TITLE
dead link to the mailing list

### ISSUE THREAD

**Issue by esahekmat** [booksbyus/zguide#721]
In Chapter 6, section 'A Real Life Example' (here: http://zguide.zeromq.org/page:all#A-Real-Life-Example) in the first line there is a link labeled 'this email thread' which point to:
http://lists.zeromq.org/pipermail/zeromq-dev/2012-October/018838.html
but this address is not accessible anymore.

**Comment by sappo** [comment]
Thanks for reporting, I'll try to find the valid link.

Am 05.03.2018 11:02 vorm. schrieb "esa hekmatizadeh" <
notifications@github.com>:

In Chapter 6, section 'A Real Life Example' (here:
http://zguide.zeromq.org/page:all#A-Real-Life-Example) in the first line
there is a link labeled 'this email thread' which point to:
http://lists.zeromq.org/pipermail/zeromq-dev/2012-October/018838.html
but this address is not accessible anymore.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/booksbyus/zguide/issues/721>, or mute the thread

**Comment by esahekmat** [comment]
finally, I found it in the mailing list archive by searching the name of the mail writer in Oct 2012, I attach a pull request #723
